// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OAuth2Fb.Models;

namespace OAuth2Fb.Migrations
{
    [DbContext(typeof(FacebookConnectContext))]
    [Migration("20200610191118_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("OAuth2Fb.Models.Email", b =>
                {
                    b.Property<int>("Email_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email_Address")
                        .HasColumnType("TEXT");

                    b.HasKey("Email_Id");

                    b.ToTable("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
